- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   
     - name: Retrieve all volumes for a queried instance
       ec2_vol:
         instance: '{{ item.id }}'
          region: eu-west-2
          state: list
       with_items: '{{ ec2.tagged_instances }}'
       register: ec2_vol

     - name: Ensure all volumes are tagged
       ec2_tag:
        region:  eu-west-1
         resource: '{{ item.id }}'
         state: present
         tags:
           Name: dbserver
           Env: production
       with_items: '{{ ec2_vol.volumes }}'

     - name: Get EC2 facts
       action: ec2_facts