---
- name: Check for CVE-2021-3156
  hosts: all
  become: true
  tasks:
    - name: Check if sudo is installed
      yum:
        list: sudo
      register: sudo_pkg
      ignore_errors: yes

    - name: Check sudo version for vulnerability
      command: "rpm -q --queryformat '%{VERSION}' sudo"
      register: sudo_version
      when: sudo_pkg|success
      changed_when: false

    - name: Generate report file
      copy:
        content: |
          Sudo is {{ 'not ' if sudo_version.stdout|version_compare('1.9', '<') else '' }}vulnerable to CVE-2021-3156
        dest: /var/log/cve_report.txt
        mode: 0644

    - name: Display result
      debug:
        msg: "Sudo is {{ 'not ' if sudo_version.stdout|version_compare('1.9', '<') else '' }}vulnerable to CVE-2021-3156"
