---
- hosts: webservers
  become: yes
  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and enabled on boot
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create Hello World webpage
      copy:
        content: "<h1>Hello World</h1>"
        dest: /var/www/html/index.html