  ---
- name: Run Updates on Terminal Servers then wait 7 mins
  hosts: terminalservers
  connection: winrm

  tasks:
    win_updates:
    - name: Install all critical and security updates
      win_updates:
        category_names:
            - Application
            - CriticalUpdates
            - DefinitionUpdates
            - SecurityUpdates
            - Updates
        state: installed
      register: update_result

    - name: Reboot host if required
      win_reboot:
      when: update_result.reboot_required

